### ISSUE TITLE
Event date appears wrong (timezones are hard)

### ISSUE THREAD

**Issue by morganestes** [wordpress-mobile/WordCamp-Android#69]
The date for WordCamp OKC is June 30, but shows up as June 29 in the app. The API returns the start epoch as 1469836800 (https://central.wordcamp.org/wp-json/posts/3040912), which is June 30 in GMT. The app seems to display the date in the local time, which means it shows up as June 29.

If the dates from the API are returned in GMT (which is a Good Thing:tm:), how do we display the correct date locally while still displaying the correct times for each session?

**Comment by iandunn** [comment]
The timestamps in the `Start Date (YYYY-mm-dd)` / `End Date (YYYY-mm-dd)` fields inside `wordcamp` posts on central.wordcamp.org are in the local timezone, just like the `_wcpt_session_time` field inside `wcb_session` posts on the individual sites. 

I don't think it makes sense for the app to consider timezones at all.

@aagam-shah, does that make sense, or is there a need to deal with timezones that I'm not seeing?

**Comment by aagam-shah** [comment]
@iandunn - As pointed out by @morganestes, if the user is in GMT– timezone it will be confusing for user to know proper dates of WordCamp. Are Start/End Dates inside wordcamp post in local timezone or in GMT, looks like it's in GMT 
WordCamp Split, Croatia `1472774400` - Fri, 02 Sep 2016 00:00:00 GMT 
WordCamp Raleigh `1474675200`  - Sat, 24 Sep 2016 00:00:00 GMT

**Comment by iandunn** [comment]
> if the user is in GMT– timezone it will be confusing for user to know proper dates of WordCamp.

So, are you saying that the app users expect the dates of camps outside their time zone to be displayed in their current time zone?

For example, if I'm in Seattle (UTC - 7) and I'm looking at the sessions for WordCamp Europe (UTC +1), should the dates be shown as June 24-26 (local time), or June 23-25 (Seattle time)?

On WordCamp.org, we don't take the visitors location into account at all, so if I browse the schedule for Europe, I see the session times in their local time zone, rather than in my time zone. I can see an argument for why that should be different in the app, but it feels a bit counter-intuitive to me.

> Are Start/End Dates inside wordcamp post in local timezone or in GMT, looks like it's in GMT 

The timestamp value like `1472774400` or `1474675200` doesn't include any particular time zone. Usually timestamps are stored in GMT, but in this case they're all the local time.

When organizers enter the session time into their sites, we don't ask them to specify a time zone, they just enter the time and we assume that it's in their local timezone. That also applies for the dates on the `wordcamp` post.

**Comment by iandunn** [comment]
(Note that Split is a bad example to look at, because their site says the event is the 3rd-4th, but it actually starts on the 2nd with some workshops, with is why Central has the start date listed on the 2nd)
