### ISSUE TITLE
WordCamp Europe missing

### ISSUE THREAD

**Issue by bph** [wordpress-mobile/WordCamp-Android#73]
Love the app! 
And the [WordCamp Europe June 15 - 18, 2017](https://2017.europe.wordcamp.org/) seems to be missing in the list. 
See screenshot here: 
![image](https://cloud.githubusercontent.com/assets/39980/26268713/9897ac44-3cbe-11e7-9523-e58876a6400e.png)

**Comment by iandunn** [comment]
This might be fixed by #72

**Comment by iandunn** [comment]
Heard more reports of this with half a dozen other camps:

https://wordpress.slack.com/archives/C08M59V3P/p1498219623150587

**Comment by marcochiesi** [comment]
It seems this problem is still present nowadays. WordCamp Europe 2018 is not listed in the app, and also a few others (i.e. Bari and Bologna).

**Comment by bph** [comment]
Screenshot of current state of mobile app
![screenshot_20180508-153453](https://user-images.githubusercontent.com/39980/39778887-98b9d2c8-52d5-11e8-8aa4-ddced30a6350.png)
From the Website
![screen shot 2018-05-08 at 3 35 21 pm](https://user-images.githubusercontent.com/39980/39778937-b660ce30-52d5-11e8-8d63-981e58cf94f8.png)

**wrong** dates: 
WC Irun was 6/1 - now 6/2
WC Orange County, CS was 6/8 is now 6/9

**Missing:** 

- WC Bari 5/11
- WC St. Louis 5/12
- WC Dayton 5/18
- WC Porto 5/18
- WC Bilbao 5/18
- WC Belfast 5/15
- WC Hamilton 6/2
- WC Osaka 6/2
more are missing.... 

The remote calendar file: https://central.wordcamp.org/calendar.ics seems to have all events listed. 
![screen shot 2018-05-08 at 3 49 48 pm](https://user-images.githubusercontent.com/39980/39779540-82d19d0e-52d7-11e8-89ca-233fec7cd2db.png)
Screeshot is from Google Calendar I just imported the above mentioned *.ics file.

**Comment by GaryJones** [comment]
I've had the same issue, where I could see WC London, but others couldn't.

In this case, from @bph's screenshot, I'm also missing Calgary, even though I just downloaded the app fresh again, having deleted it last month.

**Comment by GaryJones** [comment]
I'm not an Android or Java developer, so go with me on this:

- The query used to hit the v1 endpoint appears to be [here](https://github.com/wordpress-mobile/WordCamp-Android/blob/9a7f60b96017114a02d6dcca264855513713229e/app/src/main/java/org/wordcamp/android/networking/WPAPIClient.java#L20), and is used [here](https://github.com/wordpress-mobile/WordCamp-Android/blob/9a7f60b96017114a02d6dcca264855513713229e/app/src/main/java/org/wordcamp/android/networking/WPAPIClient.java#L35).
- This query corresponds to https://central.wordcamp.org/wp-json/posts?type=wordcamp&filter[order]=DESC&filter[posts_per_page]=50. Search the JSON to confirm that there is no WC Calgary, and no WC Europe entries.
- The querystring pulls down the last 50 `wordcamp` entries, in descending order. Note, there is no `orderby`.
- The orderby appears to default to `ID` (presumably post ID?). So WordCamps that were created early on (low post ID, and more than 50 more WCs have been registered since), but are happening soon, are not showing up.
- What appears to be missing (but is in v2 endpoints as `Start Date (YYYY-mm-dd)`), is an event date field that WC posts can be ordered by when doing the request.

I've outlined a possible approach in https://github.com/wordpress-mobile/WordCamp-Android/issues/72#issuecomment-389101355, but a quicker win would be to query for the last 100 posts, instead of 50.

**Comment by GaryJones** [comment]
Just to show, that changing to query 100 posts works (installed the Android Studio + SDK and somehow managed to get it working):

![screenshot_20180515-112630](https://user-images.githubusercontent.com/88371/40051552-1365ee8c-5833-11e8-81e7-2cb8c4e47e0b.png)

![screenshot_20180515-112645](https://user-images.githubusercontent.com/88371/40051551-134f07ee-5833-11e8-8ca3-957b882521ac.png)

All of the events that @bph identified as missing, now appear.

**Comment by bph** [comment]
Seems this is resolved. Didn't test it though.

**Comment by GaryJones** [comment]
It would only be resolved if my fix was applied - it isn't.

**Comment by bph** [comment]
After seven month of stalemate, I doubt it'll be fixed - @GaryJones Thanks for trying. Did they miss your PR?

**Comment by iandunn** [comment]
Unfortunately there isn't currently anyone on the WP mobile team who has the time to support this :(

I think PWAs are probably the future, though, so it's probably better to focus our time and energy there.

Here's a recent proposal related to that:

https://make.wordpress.org/community/2019/02/13/wordcamp-pwa-plugin-proposal-and-designs/
